### ISSUE TITLE
No pep8 or file extension

### ISSUE THREAD

**Issue by imapotatoes11** [TheRaccoon20/prime-thing-9000#1]
_off-topic_

**Comment by TheRaccoon20** [comment]
i see why my sister called you dumb

**Comment by TheRaccoon20** [comment]
ngl

**Comment by TheRaccoon20** [comment]
kindly note that i wrote this in 30 min when i was a beginner in CIF

**Comment by TheRaccoon20** [comment]
if you wanna complain go to my sister's account (notkelly1) and do that with her "hello world" project

**Comment by imapotatoes11** [comment]
I am a menace to society

**Comment by TheRaccoon20** [comment]
off-topic :)
edited :)

**Comment by TheRaccoon20** [comment]
i cannot believe you are following notkelly1 despite her 'hello world' project and yet you are still harassing me for no reason whatsoever

**Comment by imapotatoes11** [comment]
I'M DUMMMMMMMMMMMMMBBBBB!
me idiot

**Comment by TheRaccoon20** [comment]
hehehehhe 
i love editing :)

**Comment by imapotatoes11** [comment]
ME DUMB
